# Generated by Django 4.2.16 on 2025-08-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiztest', '0004_userrank_quizsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_multiple',
            field=models.BooleanField(default=False),
        ),
    ]
