# Generated by Django 4.2.16 on 2025-08-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiztest', '0005_question_is_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
